language: ruby
rvm:
  - 1.9.3
before_script:
  - "psql -c 'create database requests;' -U postgres"
  - "cp config/database.yml.travis config/database.yml"
  - "bundle exec rake db:migrate"
  - "bundle exec rake db:test:prepare"
